package com.vivohealthbridge.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFF4FD8AA)
val md_theme_dark_onPrimary = Color(0xFF003828)
val md_theme_dark_primaryContainer = Color(0xFF00513B)
val md_theme_dark_onPrimaryContainer = Color(0xFF6DF4C5)
val md_theme_dark_secondary = Color(0xFFB3CCBF)
val md_theme_dark_onSecondary = Color(0xFF1F352C)
val md_theme_dark_secondaryContainer = Color(0xFF354B42)
val md_theme_dark_onSecondaryContainer = Color(0xFFCFE9DB)
val md_theme_dark_tertiary = Color(0xFFA5CDDE)
val md_theme_dark_onTertiary = Color(0xFF063543)
val md_theme_dark_tertiaryContainer = Color(0xFF244C5A)
val md_theme_dark_onTertiaryContainer = Color(0xFFC1E9FB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1B)
val md_theme_dark_onBackground = Color(0xFFE1E3E0)
val md_theme_dark_surface = Color(0xFF191C1B)
val md_theme_dark_onSurface = Color(0xFFE1E3E0)
val md_theme_dark_surfaceVariant = Color(0xFF404945)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC9C4)
val md_theme_dark_outline = Color(0xFF89938F)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1B)
val md_theme_dark_inverseSurface = Color(0xFFE1E3E0)
val md_theme_dark_inversePrimary = Color(0xFF006C4F)
val md_theme_dark_surfaceTint = Color(0xFF4FD8AA)
val md_theme_dark_outlineVariant = Color(0xFF404945)
val md_theme_dark_scrim = Color(0xFF000000)
